### PR TITLE
Add support for absolute path references

### LINKED ISSUE #7: Support for relative URLs
It would be useful if there was a configuration setting to make the feature image URL relative to the root of the site, instead of using the full URL:

```
current:  https://okteto.com/blog/how-to-deploy-to-okteto-cloud-with-github-actions/cover.png
desired: /blog/how-to-deploy-to-okteto-cloud-with-github-actions/cover.png
```

This would be useful for the case where the same generated HTML is used on different sites (e.g. staging vs production).

Happy to submit a PR if you think this is useful. A config setting could be added to enable this, so the default behavior remains as is.

### PR DESCRIPTION
**Pull request by B3rn475**
Fixes https://github.com/poacher2k/hexo-featured-image/issues/7

### CODE REVIEW

**Comment by poacher2k** [comment]
Thank you for this! I'll review it as soon as I get the chance and merge it if everything looks good :)

**Comment by poacher2k** [comment]
Btw, @rberrelleza , does this do what you need?

**Comment by B3rn475** [comment]
Just for context:
I'm not currently able to test changes via `hexo serve` running on `localhost` as the urls link to production.
This fix solves my problem in a backwards compatible way.

**Comment by rberrelleza** [comment]
@poacher2k yes, exactly what I need! I already tested the PR and it works great on my setup.

**Comment by poacher2k** [comment]
Available in `0.4.0`, now published on `npm`

**Comment by rberrelleza** [comment]
deployed this on our site, everything works as expected. thanks!

**Pull request merged**
